### PR TITLE
fix problem set prefix & use composition API

### PR DESCRIPTION
**Pull request by drdrew42**
Update the SetProblem class to set the problem prefix on creation.

Also minor refactor to data-fetch in Instructor.vue (which will be re-evaluated later).  Essentially, move to composition API and chain our promises instead of nesting them.

### CODE REVIEW

**Comment by drdrew42** [comment]
@pstaabp this PR will fix the mathquill issues in the problem set details.

**Comment by pstaabp** [comment]
Bigger picture.  It appears that if we are using composition API via setup in vue, that the other lifecycle hooks should not be called in the same way. 

However, looking at https://vuejs.org/api/composition-api-lifecycle.html, we can use them embedded in a setup() function.  Perhaps these requests should be in a `onBeforeMount` or `onMount` function inside setup as in:

```
onMounted(() => {
   // loading requested from stores. 
})
```

**Comment by drdrew42** [comment]
The reason I didn't go for that is from the documentation:

> When this hook is called, the component has finished setting up its reactive state

Instead, we can async the setup function, await the promises, and wrap the router-view in `suspense` tags.

**Comment by pstaabp** [comment]
I'm going merge this in.  However, here's a couple of other possibilities:
1. Make sure that the stores are defined in the setup() function.  Each of the stores will have empty arrays in them.
2. in `onMount` of `beforeOnMount` load all the desired data
3. Anywhere that we want to use the data, wrap in a computed() so it reacts to changes in the store.

OR in watcher in setup() in Instructor.vue which will watch a variable to load the data.  Inside that load the data.  To trigger this code, set the trigger variables and then after data is loaded, set the trigger off. 

I guess these probably accomplish the same thing, but perhaps think about the easiest way to reload the data as needed.  For example on a course change.

**Pull request merged**
